# -*- coding: utf-8 -*-
"""Wikipedia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EGyhPGDMQv6FiKVV0uMierDiPH8k9Ya_
"""

!pip install gradio transformers wikipedia

import gradio as gr
from transformers import pipeline
import wikipedia

qa_pipeline = pipeline("question-answering", model="distilbert-base-cased-distilled-squad")

def answer_question(question, topic):
    try:
        context = wikipedia.summary(topic, sentences=5)

        result = qa_pipeline({
            'question': question,
            'context': context
        })
        answer = result['answer']

        return f"📌 Context:\n{context}\n\n💡 Answer:\n{answer}"
    except Exception as e:
        return f"Error: {str(e)}"

iface = gr.Interface(
    fn=answer_question,
    inputs=[
        gr.Textbox(label="Ask a Question", placeholder="Who is the Prime Minister of Pakistan?"),
        gr.Textbox(label="Wikipedia Topic", placeholder="Pakistan")
    ],
    outputs="text",
    title="📖 Question Answering System",
    description="Enter a question and a topic. The system will fetch a Wikipedia summary of the topic and extract the answer."
)

iface.launch()